### ISSUE TITLE
Set default repo

### ISSUE THREAD

**Issue by jasonbellamy** [jasonbellamy/git-label#8]
If a repo is not provided, I think we should assume its the repo that the script is being run in. If a repo is not provided lets grab the repo information from the current working directory.

**Comment by jasonbellamy** [comment]
Will be closed with #9

**Comment by himynameisdave** [comment]
This will read the git repo name if you want it:
[`git-repo-name`](https://www.npmjs.com/package/git-repo-name)

**Comment by jasonbellamy** [comment]
On second thought I dont know if this "default" belongs inside this API.
